version: 3

project:
  # id: sandbox
  id: test-0001
  policyId: 212700 # Camunda8 Distribution
  labels:
  - Demo
  team: 'Admin'
  # teams:
  # - 'Admin'
  url: https://github.com/clementnero/demo-licensing

maven:
  scope-exclude:
  - import
  - provided
  - system
  - test
