version: 3

project:
  # id: sandbox
  id: test
  policyId: 212700 # Camunda8 Distribution
  labels:
    - Demo
  teams:
  - Infra Team
  url: https://github.com/clementnero/demo-licensing

maven:
  scope-exclude:
  - import
  - provided
  - system
  - test
