version: 3

project:
  id: sandbox
  policy: Camunda8 Distribution
  labels:
  - Demo
  url: https://github.com/clementnero/demo-licensing

maven:
  scope-exclude:
  - import
  - provided
  - system
  - test


targets:
  exclude:
  - type: maven
    path: restapi
    target: io.camunda:test