name: License Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install FOSSA CLI
      # TODO: Add fossa-cli installation script here
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
    - name: Analyse project dependencies
      env:
        BRANCH: ${{ github.head_ref }}
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        REVISION: ${{ github.event.pull_request.head.sha }}
      run: |
        fossa analyze . --strict \
          --branch "${BRANCH}" \
          --revision "${REVISION}"
    - name: Check for new compliance issues (vs base branch)
      id: check
      env:
        BASE_REVISION: ${{ github.event.pull_request.base.sha }}
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        REVISION: ${{ github.event.pull_request.head.sha }}
      run: |
        fossa test . \
            --revision "${REVISION}" \
            --diff "${BASE_REVISION}"
    - name: New compliance issues found
      if: failure() && steps.check.conclusion == 'failure'
      env:
        BASE_REVISION: ${{ github.event.pull_request.base.sha }}
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        REVISION: ${{ github.event.pull_request.head.sha }}
      run: |
        dependencies=$(
            fossa test . \
                --revision "${REVISION}" \
                --diff "${BASE_REVISION}" \
                --format json 2>/dev/null | \
            jq -r '[.issues[].revisionId] | unique | join(", ")'
        )
        echo "::error line=1:: findings are to be review in fossa.com (more in logs) for deps: ${dependencies}"
        echo "::error line=2:: findings are to be review in fossa.com (more in logs) for deps: ${dependencies}"
