name: Checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install fossa
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
    - name: FOSS analysis
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        BRANCH: ${{ github.head_ref }}
      run: |
        fossa analyze . --strict --branch "${BRANCH}"
    - name: Checking fornew findings
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        BASE_REVISION: ${{ github.event.pull_request.base.sha }}
      run: |
        fossa test . --diff "${BASE_REVISION}"
