name: License Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: .github/actions/fossa/analyze
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
        branch: ${{ github.head_ref || github.ref_name }}
        revision-id: ${{ github.sha }}
