name: License Check

on:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup fossa-cli
      uses: clementnero/demo-licensing/.github/actions/fossa/setup@add-licensing-checks
    - name: Analyze project
      uses: clementnero/demo-licensing/.github/actions/fossa/analyze@add-licensing-checks
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
        branch: ${{ github.ref_name }} # available for push events
        revision-id: ${{ github.sha }} # available for push events
