name: fossa analyze

description: Run FOSSA CLI analyze command

inputs:
  api-key:
    description: The API key for FOSSA
    required: true
  branch:
    description: Name of the branch to be scanned
    required: true
  revision-id:
    description: ID of the revision to be scanned
    required: true
runs:
  using: composite
  steps:
    - name: Install FOSSA CLI
      env:
        # renovate: datasource=github-releases depName=fossas/fossa-cli
        FOSSA_CLI_VERSION: 3.10.2
      run: |
        if ! command -v fossa &> /dev/null
        then
          echo "FOSSA CLI not found, installing version=${FOSSA_CLI_VERSION}..."
          curl \
            -sSL \
            -H 'Cache-Control: no-cache' \
            https://github.com/fossas/fossa-cli/releases/download/v${FOSSA_CLI_VERSION}/fossa_${FOSSA_CLI_VERSION}_linux_amd64.tar.gz | \
            tar -xz -C /usr/local/bin
        else
          echo "FOSSA CLI is already installed"
        fi
      shell: bash
    - name: Run FOSSA analyze
      env:
        BRANCH: ${{ inputs.branch }}
        FOSSA_API_KEY: ${{ inputs.api-key }}
        REVISION_ID: ${{ inputs.analyze-revision-id }}
      run: |
        fossa analyze . \
          --strict \
          --branch "${BRANCH}" \
          --revision "${REVISION_ID}"
      shell: bash
