name: fossa analyze

description: Run FOSSA CLI analyze command

inputs:
  api-key:
    description: The API key for FOSSA
    required: true
  branch:
    description: Name of the branch to be scanned
    required: true
  revision-id:
    description: ID of the revision to be scanned
    required: true
runs:
  using: composite
  steps:
    - name: Install FOSSA CLI
      uses: .github/actions/fossa/setup
      # uses: clementnero/demo-licensing/.github/actions/fossa/analyze@add-licensing-checks
    - name: Run FOSSA analyze
      env:
        BRANCH: ${{ inputs.branch }}
        FOSSA_API_KEY: ${{ inputs.api-key }}
        REVISION_ID: ${{ inputs.analyze-revision-id }}
      run: |
        fossa analyze . \
          --strict \
          --branch "${BRANCH}" \
          --revision "${REVISION_ID}"
      shell: bash
